import Head from "next/head";
import { useRouter } from "next/router";

import Layout from "@/components/layout/layout";
import Vendors from "@/components/vendors/vendors";

export default function Vendor() {
  const router = useRouter();
  const { query } = router;
  const { collectionId = "unknown" } = query;

  return (
    <>
      <Head>
        <title>Vendors</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Vendors />
      </Layout>
    </>
  );
}
